name: environmental_python
channels:
  - conda-forge
  - defaults

dependencies:
  # --- Core Python and Jupyter ---
  - python=3.10
  - ipykernel
  - jupyterlab
  - ipywidgets

  # --- Data manipulation and scientific computing ---
  - numpy
  - pandas
  - xarray
  - scipy
  - statsmodels
  - scikit-learn
  - scikit-bio

  # --- Visualization ---
  - matplotlib
  - seaborn

  # --- Utilities and code formatting ---
  - black
  - pip
  - nbstripout
  - nbdime

  # --- Pip-only packages ---
  - pip:
      - factor_analyzer
      - scikit-posthocs
